name: wasm-pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: compile wasm
      run: |
        wasm-pack build --target web --out-dir build/pkg
        cp index.html ./build
        ls -al ./build
        echo "are you ok? wtf are you doing? can you deploy this motherfucking directory or what ??"
        echo "ffs, just fuck u"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: build
