name: wasm-pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: compile wasm
      run: wasm-pack build --target web
    - run: mkdir dist
    - run: mv index.html dist/
    - run: mv pkg dist/
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
