name: wasm-pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: compile wasm
      run: wasm-pack build --target web
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          index.html
          pkg/
    - uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
