name: wasm-pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: compile wasm
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "github action"
        git fetch
        rm -rf ./docs
        wasm-pack build --target web
        git checkout -b built
        git add .
        git commit -m "built"
        git checkout gh-pages
        git merge built
        git push
