name: wasm-pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
    - name: compile wasm
      run: wasm-pack build --target web
    - name: git add
      run: git add ./pkg
    - name: Push to gh-pages
      uses: Automattic/action-commit-to-branch@master
      with:
        branch: 'gh-pages'
        commit_message: '[action] wasm-pack build'
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }} # Required
